In [18]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [19]:
from src.feature_engineering import create_order_item_features
import pandas as pd
from src.config import PROCESSED_DATA_DIR

In [20]:
order_items = pd.read_csv(PROCESSED_DATA_DIR / "order_items_cleaned.csv")

In [21]:
order_item_features = create_order_item_features(order_items)
order_item_features.head()

,order_id,item_count,unique_products,product_revenue,freight_cost
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,1,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,1,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,1,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,199.90,18.14

In [22]:
order_item_features.shape

(98666, 5)

In [23]:
order_item_features['order_id'].duplicated().sum()

np.int64(0)

In [24]:
from src.feature_engineering import create_payment_features

In [25]:
payments = pd.read_csv(PROCESSED_DATA_DIR / "payments_cleaned.csv")

In [26]:
payment_features = create_payment_features(payments)
payment_features.head()

,order_id,payment_count,total_payment_value,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,1,72.19,2
1,00018f77f2f0320c557190d7a144bdd3,1,259.83,3
2,000229ec398224ef6ca0657da4fc703e,1,216.87,5
3,00024acbcdf0a6daa1e931b038114c75,1,25.78,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,218.04,3

In [27]:
payment_features.shape

(99440, 4)

In [28]:
payment_features['order_id'].duplicated().sum()

np.int64(0)

In [29]:
from src.feature_engineering import create_review_features

In [30]:
reviews = pd.read_csv(PROCESSED_DATA_DIR / 'reviews_cleaned.csv')
review_features = create_review_features(reviews)

In [31]:
review_features.head()

,order_id,review_count,average_review_score,negative_review
0,00010242fe8c5a6d1ba2dd792cb16214,1,5.0,0
1,00018f77f2f0320c557190d7a144bdd3,1,4.0,0
2,000229ec398224ef6ca0657da4fc703e,1,5.0,0
3,00024acbcdf0a6daa1e931b038114c75,1,4.0,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,5.0,0

In [32]:
review_features.shape

(98673, 4)

In [33]:
review_features['order_id'].duplicated().sum()

np.int64(0)

In [36]:
review_features.head(10)

,order_id,review_count,average_review_score,negative_review
0,00010242fe8c5a6d1ba2dd792cb16214,1,5.0,0
1,00018f77f2f0320c557190d7a144bdd3,1,4.0,0
2,000229ec398224ef6ca0657da4fc703e,1,5.0,0
3,00024acbcdf0a6daa1e931b038114c75,1,4.0,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,5.0,0
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,4.0,0
6,00054e8431b9d7675808bcb819fb4a32,1,4.0,0
7,000576fe39319847cbb9d288c5617fa6,1,5.0,0
8,0005a1a1728c9d785b8e2b08b904576c,1,1.0,1
9,0005f50442cb953dcd1d21e1fb923495,1,4.0,0

In [38]:
review_features.duplicated().sum()

np.int64(0)

In [39]:
review_features.isnull().sum()

order_id                0
review_count            0
average_review_score    0
negative_review         0
dtype: int64

In [45]:
review_features['negative_review'].nunique()

2

In [47]:
review_features['negative_review'].value_counts()

negative_review
0    84140
1    14533
Name: count, dtype: int64

In [48]:
review_features['review_count'].value_counts()

review_count
1    98126
2      543
3        4
Name: count, dtype: int64

## Review_features findings

- there are no duplicated records in the review_features
- thus all rows represents reviews of per order grouped by order_id 
- the review count holds three distinct value 1,2,3 based on order_id 
- there are no null values in the review_features table